### ISSUE TITLE
New versions in TER

### ISSUE THREAD

**Issue by spoonerWeb** [beechit/default_upload_folder#26]
The latest version in TER is 1.0.1, in this repository it's 1.2.0.
Was it your intention to not update the extension in TER?

Would be nice to have up-to-date versions in TER as well. 👍

**Comment by sgrossberndt** [comment]
Altough a [TER tailor config has been added](https://github.com/beechit/default_upload_folder/commit/51bd208da98de966972d12c2cfb0f5583a30fda1) the TER still shows v1.0.1 as there has not been a new release yet.
Could you manually trigger the release to TER please?

**Comment by joey-bolts** [comment]
@sgrossberndt @spoonerWeb 

Release has been made. 

https://extensions.typo3.org/extension/default_upload_folder
