### ISSUE TITLE
Type Error when trying to work with text and image element

### ISSUE THREAD

**Issue by chrisprog20** [beechit/default_upload_folder#29]
Version: TYPO3 9.5.27

Thank you first for this great extension. It helped me to keep the upload folders in our extensions for TYPO3 >= 10.

I just discovered that our editor got a Type Error message when trying to edit the Text-and-Image element.
The function getDefaultUploadFolder returned an empty string while a Folder object was expected. After removing the return type the editor could again work with the text and image element.

I have to also add the information that I did not provide in pageTSConfig a defaultForAllTables setting as my default for all tables is the TYPO3 core default "fileadmin/user_upload/".

**Comment by tbsschmdt** [comment]
Pull request #27 should fix this.

**Comment by chrisprog20** [comment]
Thank you @tbsschmdt for your quick reply. This pull request fixed it! :-) Thank you for it! :-) Hope it will soon be merged into master!

**Comment by joey-bolts** [comment]
PR #27 is merged and released.

@tbsschmdt Thank you for this pull request.
