### ISSUE TITLE
syntax error, unexpected token "{", expecting ")" after Updating to 1.2.3 under TYPO3 11

### ISSUE THREAD

**Issue by stephangrass** [beechit/default_upload_folder#34]
Hi
under TYPO3 11 version 1.2.2 of your extension will work. After updating to 1.2.3 I get ther error

`syntax error, unexpected token "{", expecting ")"`

**Comment by joey-bolts** [comment]
@stephangrass Do you have a class and line?

**Comment by joey-bolts** [comment]
@stephangrass Nevermind, found it. Fixing and releasing now. https://github.com/beechit/default_upload_folder/blob/5eb621d5d52bab10e5becb01dba49a2b50263417/Classes/Hooks/DefaultUploadFolder.php#L106

**Comment by joey-bolts** [comment]
@stephangrass Should be resolved now. 1.2.5
