### ISSUE TITLE
Use of static class method call "TYPO3\CMS\Core\Resource\ResourceFactory::getInstance()"

### ISSUE THREAD

**Issue by abvdveen** [beechit/default_upload_folder#37]
There is a static call in function createUploadFolder that should be replaced:
`$uploadFolder = ResourceFactory::getInstance()->getFolderObjectFromCombinedIdentifier`
should be:
`GeneralUtility::makeInstance(ResourceFactory::class)->getFolderObjectFromCombinedIdentifier`

**Comment by ruudsilvrants** [comment]
This is resolved by https://github.com/beechit/default_upload_folder/commit/79ea42a0b40a11d663d2c1a7791c00c8797db463
