### ISSUE TITLE
Code is exited too early if users do not have default upload folders

### ISSUE THREAD

**Issue by franzkugelmann** [beechit/default_upload_folder#38]
We found a regression introduced with https://github.com/beechit/default_upload_folder/pull/27.
There the following statement was made:

> If a backend user has no file mount at all and therefore no permission to access any folder it makes no sense to set a default upload folder. In such cases parameter uploadFolder is the empty string or null and method getDefaultUploadFolder should return immediately.

The assumption is wrong though. If the incoming parameter uploadFolder is empty or null that does not mean the user has no permission to folders at all. It does mean the user has no access to the default upload folder of any storage.
Every user which has no global access to the fileadmin but only to subfolders (via file mounts) and no group or user based default upload folder falls into that category.
We have a project where we define the upload folder only based on page tree, not on user or group base, which is why we use this nice extension in the first place.

**Comment by tbsschmdt** [comment]
I made this bold statement you quoted and can confirm that I did not take the configuration setup you described into account with my changes. I can confirm your changes fix the regression.

Could you please add a second catch block for InsufficientFolderAccessPermissionsException to your fix:

```PHP
use TYPO3\CMS\Core\Resource\Exception\InsufficientFolderAccessPermissionsException;

// ...

// Folder by combined identifier
if (preg_match('/[0-9]+:/', $subFolder)) {
    try {
        $uploadFolder = GeneralUtility::makeInstance(ResourceFactory::class)->getFolderObjectFromCombinedIdentifier(
            $subFolder
        );
    } catch (FolderDoesNotExistException $e) {
        $uploadFolder = $this->createUploadFolder($subFolder);
    } catch (InsufficientFolderAccessPermissionsException $e) {
        $uploadFolder = null;
    }
}
```

This catch block prevents an error message if a user has no access to the configured upload folder.

**Comment by franzkugelmann** [comment]
Hi @tbsschmdt, thanks for the quick confirmation. I added your suggestion and confirm that it works as described.

**Comment by joey-bolts** [comment]
@franzkugelmann @tbsschmdt 

Thanks for the PR, we will look into this soon.

**Comment by aaxc** [comment]
Can confirm, updated yesterday and lots of users lost their access. Corrently did a rollback to a previous version, but waiting for an official fix

**Comment by joey-bolts** [comment]
@aaxc By can confirm, do you mean this PR does or does not resolve it?

**Comment by aaxc** [comment]
Resolves. I'm still using older version for live system, that I rollbacked to, but this solved the issue on test system, but I don't want to put it on live, till it's official.

**Comment by joey-bolts** [comment]
@aaxc Oke, thanks for elaboration.

**Comment by ruudsilvrants** [comment]
Hello @franzkugelmann ,

I want to open a small discussion about the MR;
- If the folder can not be created or you return null. what do you expect of the fallback? I.m.o. you do want an error due the fact this means a misconfiguration. The user should not fallback to default user_upload folder.

**Comment by franzkugelmann** [comment]
@ruudsilvrants You are relating to the second catch block i added as reaction to the suggestion of @tbsschmdt?  I thought about that too. Is it better to throw an error blocking the user and making clear there is probably an issue or let the editor just work? In the end i tend to let the editor just work. She will maybe miss the direct_upload buttons (and in that case inform the admins about the issue), but can work on the content unhindered.
With that non-catched exception, there is no way to edit the content, even if it is not about uploading files at all.

**Comment by ruudsilvrants** [comment]
@franzkugelmann Yes, referring to the second catch block. My thoughts was that the user still could upload files only to the "default" folder of typo3 installation. (usually user_upload). But this was a wrong assumption. 
When returning `null` the upload button is not available which seems a good situation. 

Approving the MR and merging this in a new release.
