### ISSUE TITLE
typo3 9 update?

### ISSUE THREAD

**Issue by X-Tender** [beechit/default_upload_folder#4]
Would it be possible to update it vor v9 ?

**Comment by frans-beech-it** [comment]
The extension should be 9LTS compatible. Did you try it already?

**Comment by frans-beech-it** [comment]
See 0ea9e50cdae64dc7b1193dfe1305ddd773eecacb

**Comment by X-Tender** [comment]
Sure I could do it via the manual way but I use the composer installation way so I had to do it always manualy :)

**Comment by frans-beech-it** [comment]
new version tagged
