### ISSUE TITLE
Documentation links to version 1.0.0

### ISSUE THREAD

**Issue by klodeckl** [beechit/default_upload_folder#42]
The link to the documentation (TER and extension manager) links to version 1.0.0 and not to the current version. How to get to the docs of the current version?

**Comment by support-beech** [comment]
@klodeckl 

Current  [readme](https://github.com/beechit/default_upload_folder/blob/master/README.md) is the latest documentation.

**Comment by klodeckl** [comment]
I know, but why is the old version linked?

**Comment by FamousWolf** [comment]
We've updated the documentation link in TER now. Thanks for pointing it out.
