### ISSUE TITLE
Php warning in impexp with php 8

### ISSUE THREAD

**Issue by dogawaf** [beechit/default_upload_folder#44]
TYPO3 11
PHP 8.0

This warning occurs in impexp module (export t3d):

`PHP Warning: Undefined array key "table" in /var/www/html/web/typo3conf/ext/default_upload_folder/Classes/Hooks/DefaultUploadFolder.php line 34`

This is because the getDefaultUploadFolder hook can be called with null table/field.

ext:default_upload_folder should handle this case, and return the result of getDefaultUploadFolderForAllTables

**Comment by support-beech** [comment]
@dogawaf 

Since this is a warning this is not highest on our priority list. Thanks for creating the issue.
If you would like a fix on short term, we would appreciate a pull request.

Thanks.
