### ISSUE TITLE
Namespace declaration for interface FolderInterface is missing

### ISSUE THREAD

**Issue by weberdigital** [beechit/default_upload_folder#53]
Hi,

in [Classes/EventListener/Backend/DefaultUploadFolder.php](https://github.com/beechit/default_upload_folder/blob/37a9bea0276c6f381c246cbe07fe49402cb9609a/Classes/EventListener/Backend/DefaultUploadFolder.php#L6)
the namespace declaration `TYPO3\CMS\Core\Resource\FolderInterface` is missing.

Therefore the upload folder was not set in https://github.com/beechit/default_upload_folder/blob/37a9bea0276c6f381c246cbe07fe49402cb9609a/Classes/EventListener/Backend/DefaultUploadFolder.php#L64-L66

Thanks for fixing the issue.

**Comment by support-beech** [comment]
@weberdigital Thanks.
