### ISSUE TITLE
Not working for properties of configured page

### ISSUE THREAD

**Issue by mbrodala** [beechit/default_upload_folder#6]
We have configured `default_upload_folders` on the root page but oddly it does not work for properties of that page itself, e.g. the *Media* field on the *Resources* tab.

It works just fine for pages within as well as content however.

Here our very simple configuration:

```
default_upload_folders {
    pages = 1:foo
    tt_content = 1:foo
}
```

Any idea?

**Comment by frans-beech-it** [comment]
Fixed with #19
