### ISSUE TITLE
config works if tablename is used, but defaultForAllTables gets ignored

### ISSUE THREAD

**Issue by jpmschuler** [beechit/default_upload_folder#8]
I am new to this wonderful extension, but can't make `defaultForAllTables` work. I tried it with a simple test as described below. Am I missing something?
### What works
In a 8LTS I manually set page.TSconfig for a branch like
```
default_upload_folders.tt_content = 1:fileupload/myfolder
```
On a subpage of this branch I edit a textpic and click "Add Images" on the image tab. The folder ` fileadmin/fileupload/myfolder/` is opened.
### What doesn't work
In a 8LTS I manually set page.TSconfig for a branch like
```
default_upload_folders.defaultForAllTables = 1:fileupload/myfolder
```
On a subpage of this branch I edit a textpic and click "Add Images" on the image tab. The folder ` fileadmin/user_upload/` is opened (fallback to TYPO3 default), although `fileadmin/fileupload/myfolder` was expected.

**Comment by joey-bolts** [comment]
@jpmschuler Could you please verify above bugfix and update. 

Please let us know the result, so we can close this issue.

**Comment by jpmschuler** [comment]
I just tried it in a 8LTS. Behavior fixed. 
The problem was present in 9LTS as well. The MR/patch resolves the behavior there too.
